swagger: "2.0"
tags:
- name: "Login"
  description: "Login 관련 API"
paths:
  /jwttest/login:
    post:
      tags:
      - "Login"
      summary: "로그인"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "body"
        in: "body"
        required: true
        schema:
            $ref: "#/definitions/LoginParam"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
  
definitions:
  LoginParam:
    type: "object"
    required:
    - "id"
    - "pw"
    properties:
      id:
        type: "string"
        description: "로그인 ID"
      pw:
        type: "string"
        description: "로그인 PW"
  ApiResponse:
    type: "object"
    properties:
      messageInfo:
        type: "object"
        properties:
          code:
            type: "integer"
            format: "int32"
          message:
            type: "string"
      record:
        type: "object"
